version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379  
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
