name: Build and Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: disasteracr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t disasteracr.azurecr.io/disaster_api:latest .
        docker push disasteracr.azurecr.io/disaster_api:latest

    - name: Deploy to Azure Web App (Docker)
      uses: azure/webapps-deploy@v2
      with:
        app-name: disaster-api-app
        images: disasteracr.azurecr.io/disaster_api:latest
