name: Build and Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Docker Hub (or Azure Registry)
      uses: azure/docker-login@v1
      with:
        login-server: disaster_api.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t disaster_api.azurecr.io/disaster_api:latest .
        docker push disaster_api.azurecr.io/disaster_api:latest

    - name: Deploy to Azure Web App (Docker)
      uses: azure/webapps-deploy@v2
      with:
        app-name: disaster_api
        images: disaster_api.azurecr.io/disaster_api:latest
